const BASE_URL =
  '/proxy/moz-fx-translations-data--303e-prod-translations-data';

const LANGUAGES = [
  { code: 'sq', name: 'Albanian' },
  { code: 'ar', name: 'Arabic' },
  { code: 'az', name: 'Azerbaijani' },
  { code: 'be', name: 'Belarusian' },
  { code: 'bn', name: 'Bengali' },
  { code: 'bs', name: 'Bosnian' },
  { code: 'bg', name: 'Bulgarian' },
  { code: 'ca', name: 'Catalan' },
  { code: 'zh', name: 'Chinese (简体)' },
  { code: 'zh_hant', name: 'Chinese (繁體)' },
  { code: 'hr', name: 'Croatian' },
  { code: 'cs', name: 'Czech' },
  { code: 'da', name: 'Danish' },
  { code: 'nl', name: 'Dutch' },
  { code: 'en', name: 'English' },
  { code: 'et', name: 'Estonian' },
  { code: 'fi', name: 'Finnish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'el', name: 'Greek' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'he', name: 'Hebrew' },
  { code: 'hi', name: 'Hindi' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'is', name: 'Icelandic' },
  { code: 'id', name: 'Indonesian' },
  { code: 'it', name: 'Italian' },
  { code: 'ja', name: 'Japanese' },
  { code: 'kn', name: 'Kannada' },
  { code: 'ko', name: 'Korean' },
  { code: 'lv', name: 'Latvian' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'ms', name: 'Malay' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'no', name: 'Norwegian' },
  { code: 'nb', name: 'Norwegian Bokmål' },
  { code: 'nn', name: 'Norwegian Nynorsk' },
  { code: 'fa', name: 'Persian' },
  { code: 'pl', name: 'Polish' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ro', name: 'Romanian' },
  { code: 'ru', name: 'Russian' },
  { code: 'sr', name: 'Serbian' },
  { code: 'sk', name: 'Slovak' },
  { code: 'sl', name: 'Slovenian' },
  { code: 'es', name: 'Spanish' },
  { code: 'sv', name: 'Swedish' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'th', name: 'Thai' },
  { code: 'tr', name: 'Turkish' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'vi', name: 'Vietnamese' },
];

// fromEnglishFiles: en -> lang
const FROM_ENGLISH = {
  ar: { model: 'model.enar.intgemm.alphas.bin', srcVocab: 'vocab.enar.spm', tgtVocab: 'vocab.enar.spm', lex: 'lex.50.50.enar.s2t.bin', paths: { 'model.enar.intgemm.alphas.bin': 'models/en-ar/retrain_base-memory_G3CmhwG_TZext3cys-udHg/exported/model.enar.intgemm.alphas.bin.gz', 'vocab.enar.spm': 'models/en-ar/retrain_base-memory_G3CmhwG_TZext3cys-udHg/exported/vocab.enar.spm.gz', 'vocab.enar.spm': 'models/en-ar/retrain_base-memory_G3CmhwG_TZext3cys-udHg/exported/vocab.enar.spm.gz', 'lex.50.50.enar.s2t.bin': 'models/en-ar/retrain_base-memory_G3CmhwG_TZext3cys-udHg/exported/lex.50.50.enar.s2t.bin.gz' } },
  az: { model: 'model.enaz.intgemm.alphas.bin', srcVocab: 'vocab.enaz.spm', tgtVocab: 'vocab.enaz.spm', lex: 'lex.50.50.enaz.s2t.bin', paths: { 'model.enaz.intgemm.alphas.bin': 'models/en-az/h1-2025_fu1HFuR0QY-zVBcKYQkJIA/exported/model.enaz.intgemm.alphas.bin.gz', 'vocab.enaz.spm': 'models/en-az/h1-2025_fu1HFuR0QY-zVBcKYQkJIA/exported/vocab.enaz.spm.gz', 'vocab.enaz.spm': 'models/en-az/h1-2025_fu1HFuR0QY-zVBcKYQkJIA/exported/vocab.enaz.spm.gz', 'lex.50.50.enaz.s2t.bin': 'models/en-az/h1-2025_fu1HFuR0QY-zVBcKYQkJIA/exported/lex.50.50.enaz.s2t.bin.gz' } },
  bg: { model: 'model.enbg.intgemm.alphas.bin', srcVocab: 'vocab.enbg.spm', tgtVocab: 'vocab.enbg.spm', lex: 'lex.50.50.enbg.s2t.bin', paths: { 'model.enbg.intgemm.alphas.bin': 'models/en-bg/retrain_hr_eAF9fkYRScmBmvvfdT4XWw/exported/model.enbg.intgemm.alphas.bin.gz', 'vocab.enbg.spm': 'models/en-bg/retrain_hr_eAF9fkYRScmBmvvfdT4XWw/exported/vocab.enbg.spm.gz', 'vocab.enbg.spm': 'models/en-bg/retrain_hr_eAF9fkYRScmBmvvfdT4XWw/exported/vocab.enbg.spm.gz', 'lex.50.50.enbg.s2t.bin': 'models/en-bg/retrain_hr_eAF9fkYRScmBmvvfdT4XWw/exported/lex.50.50.enbg.s2t.bin.gz' } },
  bn: { model: 'model.enbn.intgemm.alphas.bin', srcVocab: 'vocab.enbn.spm', tgtVocab: 'vocab.enbn.spm', lex: 'lex.50.50.enbn.s2t.bin', paths: { 'model.enbn.intgemm.alphas.bin': 'models/en-bn/h1-2025_TYlSskC_Sk6lBlfWRetXmg/exported/model.enbn.intgemm.alphas.bin.gz', 'vocab.enbn.spm': 'models/en-bn/h1-2025_TYlSskC_Sk6lBlfWRetXmg/exported/vocab.enbn.spm.gz', 'vocab.enbn.spm': 'models/en-bn/h1-2025_TYlSskC_Sk6lBlfWRetXmg/exported/vocab.enbn.spm.gz', 'lex.50.50.enbn.s2t.bin': 'models/en-bn/h1-2025_TYlSskC_Sk6lBlfWRetXmg/exported/lex.50.50.enbn.s2t.bin.gz' } },
  bs: { model: 'model.enbs.intgemm.alphas.bin', srcVocab: 'vocab.enbs.spm', tgtVocab: 'vocab.enbs.spm', lex: 'lex.50.50.enbs.s2t.bin', paths: { 'model.enbs.intgemm.alphas.bin': 'models/en-bs/hbs-topk10_HBBkp2ozSYaY9f7WVGRtpA/exported/model.enbs.intgemm.alphas.bin.gz', 'vocab.enbs.spm': 'models/en-bs/hbs-topk10_HBBkp2ozSYaY9f7WVGRtpA/exported/vocab.enbs.spm.gz', 'vocab.enbs.spm': 'models/en-bs/hbs-topk10_HBBkp2ozSYaY9f7WVGRtpA/exported/vocab.enbs.spm.gz', 'lex.50.50.enbs.s2t.bin': 'models/en-bs/hbs-topk10_HBBkp2ozSYaY9f7WVGRtpA/exported/lex.50.50.enbs.s2t.bin.gz' } },
  ca: { model: 'model.enca.intgemm.alphas.bin', srcVocab: 'vocab.enca.spm', tgtVocab: 'vocab.enca.spm', lex: 'lex.50.50.enca.s2t.bin', paths: { 'model.enca.intgemm.alphas.bin': 'models/en-ca/short-sentences_dqpjVFEaT2WLVB2nV0_H2g/exported/model.enca.intgemm.alphas.bin.gz', 'vocab.enca.spm': 'models/en-ca/short-sentences_dqpjVFEaT2WLVB2nV0_H2g/exported/vocab.enca.spm.gz', 'vocab.enca.spm': 'models/en-ca/short-sentences_dqpjVFEaT2WLVB2nV0_H2g/exported/vocab.enca.spm.gz', 'lex.50.50.enca.s2t.bin': 'models/en-ca/short-sentences_dqpjVFEaT2WLVB2nV0_H2g/exported/lex.50.50.enca.s2t.bin.gz' } },
  cs: { model: 'model.encs.intgemm.alphas.bin', srcVocab: 'vocab.encs.spm', tgtVocab: 'vocab.encs.spm', lex: 'lex.50.50.encs.s2t.bin', paths: { 'model.encs.intgemm.alphas.bin': 'models/en-cs/retrain_hr_F_JF0vqvSjSwn3caQQcicA/exported/model.encs.intgemm.alphas.bin.gz', 'vocab.encs.spm': 'models/en-cs/retrain_hr_F_JF0vqvSjSwn3caQQcicA/exported/vocab.encs.spm.gz', 'vocab.encs.spm': 'models/en-cs/retrain_hr_F_JF0vqvSjSwn3caQQcicA/exported/vocab.encs.spm.gz', 'lex.50.50.encs.s2t.bin': 'models/en-cs/retrain_hr_F_JF0vqvSjSwn3caQQcicA/exported/lex.50.50.encs.s2t.bin.gz' } },
  da: { model: 'model.enda.intgemm.alphas.bin', srcVocab: 'vocab.enda.spm', tgtVocab: 'vocab.enda.spm', lex: 'lex.50.50.enda.s2t.bin', paths: { 'model.enda.intgemm.alphas.bin': 'models/en-da/spring-2024_XUm0Ij8WSfabkKeKA_Xv_g/exported/model.enda.intgemm.alphas.bin.gz', 'vocab.enda.spm': 'models/en-da/spring-2024_XUm0Ij8WSfabkKeKA_Xv_g/exported/vocab.enda.spm.gz', 'vocab.enda.spm': 'models/en-da/spring-2024_XUm0Ij8WSfabkKeKA_Xv_g/exported/vocab.enda.spm.gz', 'lex.50.50.enda.s2t.bin': 'models/en-da/spring-2024_XUm0Ij8WSfabkKeKA_Xv_g/exported/lex.50.50.enda.s2t.bin.gz' } },
  de: { model: 'model.ende.intgemm.alphas.bin', srcVocab: 'vocab.ende.spm', tgtVocab: 'vocab.ende.spm', lex: 'lex.50.50.ende.s2t.bin', paths: { 'model.ende.intgemm.alphas.bin': 'models/en-de/retrain_hr_fix_names_SCgGhxUPQ2WAECHLRtzrMg/exported/model.ende.intgemm.alphas.bin.gz', 'vocab.ende.spm': 'models/en-de/retrain_hr_fix_names_SCgGhxUPQ2WAECHLRtzrMg/exported/vocab.ende.spm.gz', 'vocab.ende.spm': 'models/en-de/retrain_hr_fix_names_SCgGhxUPQ2WAECHLRtzrMg/exported/vocab.ende.spm.gz', 'lex.50.50.ende.s2t.bin': 'models/en-de/retrain_hr_fix_names_SCgGhxUPQ2WAECHLRtzrMg/exported/lex.50.50.ende.s2t.bin.gz' } },
  el: { model: 'model.enel.intgemm.alphas.bin', srcVocab: 'vocab.enel.spm', tgtVocab: 'vocab.enel.spm', lex: 'lex.50.50.enel.s2t.bin', paths: { 'model.enel.intgemm.alphas.bin': 'models/en-el/spring-2024_Y3ThG3XkTxG4ROUQK2LpVg/exported/model.enel.intgemm.alphas.bin.gz', 'vocab.enel.spm': 'models/en-el/spring-2024_Y3ThG3XkTxG4ROUQK2LpVg/exported/vocab.enel.spm.gz', 'vocab.enel.spm': 'models/en-el/spring-2024_Y3ThG3XkTxG4ROUQK2LpVg/exported/vocab.enel.spm.gz', 'lex.50.50.enel.s2t.bin': 'models/en-el/spring-2024_Y3ThG3XkTxG4ROUQK2LpVg/exported/lex.50.50.enel.s2t.bin.gz' } },
  es: { model: 'model.enes.intgemm.alphas.bin', srcVocab: 'vocab.enes.spm', tgtVocab: 'vocab.enes.spm', lex: 'lex.50.50.enes.s2t.bin', paths: { 'model.enes.intgemm.alphas.bin': 'models/en-es/retrain_hr_fix_names_CUAEXUHoQum_cFqh-ZAryw/exported/model.enes.intgemm.alphas.bin.gz', 'vocab.enes.spm': 'models/en-es/retrain_hr_fix_names_CUAEXUHoQum_cFqh-ZAryw/exported/vocab.enes.spm.gz', 'vocab.enes.spm': 'models/en-es/retrain_hr_fix_names_CUAEXUHoQum_cFqh-ZAryw/exported/vocab.enes.spm.gz', 'lex.50.50.enes.s2t.bin': 'models/en-es/retrain_hr_fix_names_CUAEXUHoQum_cFqh-ZAryw/exported/lex.50.50.enes.s2t.bin.gz' } },
  et: { model: 'model.enet.intgemm.alphas.bin', srcVocab: 'vocab.enet.spm', tgtVocab: 'vocab.enet.spm', lex: 'lex.50.50.enet.s2t.bin', paths: { 'model.enet.intgemm.alphas.bin': 'models/en-et/retrain_hr_GubU3EaMRY2VkR8p1dPUNw/exported/model.enet.intgemm.alphas.bin.gz', 'vocab.enet.spm': 'models/en-et/retrain_hr_GubU3EaMRY2VkR8p1dPUNw/exported/vocab.enet.spm.gz', 'vocab.enet.spm': 'models/en-et/retrain_hr_GubU3EaMRY2VkR8p1dPUNw/exported/vocab.enet.spm.gz', 'lex.50.50.enet.s2t.bin': 'models/en-et/retrain_hr_GubU3EaMRY2VkR8p1dPUNw/exported/lex.50.50.enet.s2t.bin.gz' } },
  fa: { model: 'model.enfa.intgemm.alphas.bin', srcVocab: 'vocab.enfa.spm', tgtVocab: 'vocab.enfa.spm', lex: 'lex.50.50.enfa.s2t.bin', paths: { 'model.enfa.intgemm.alphas.bin': 'models/en-fa/h1-2025_c_TYU1BOTByxOnnkAunO7g/exported/model.enfa.intgemm.alphas.bin.gz', 'vocab.enfa.spm': 'models/en-fa/h1-2025_c_TYU1BOTByxOnnkAunO7g/exported/vocab.enfa.spm.gz', 'vocab.enfa.spm': 'models/en-fa/h1-2025_c_TYU1BOTByxOnnkAunO7g/exported/vocab.enfa.spm.gz', 'lex.50.50.enfa.s2t.bin': 'models/en-fa/h1-2025_c_TYU1BOTByxOnnkAunO7g/exported/lex.50.50.enfa.s2t.bin.gz' } },
  fi: { model: 'model.enfi.intgemm.alphas.bin', srcVocab: 'vocab.enfi.spm', tgtVocab: 'vocab.enfi.spm', lex: 'lex.50.50.enfi.s2t.bin', paths: { 'model.enfi.intgemm.alphas.bin': 'models/en-fi/retrain_hr_b45LsGaNQFyDRhHAvBbKrA/exported/model.enfi.intgemm.alphas.bin.gz', 'vocab.enfi.spm': 'models/en-fi/retrain_hr_b45LsGaNQFyDRhHAvBbKrA/exported/vocab.enfi.spm.gz', 'vocab.enfi.spm': 'models/en-fi/retrain_hr_b45LsGaNQFyDRhHAvBbKrA/exported/vocab.enfi.spm.gz', 'lex.50.50.enfi.s2t.bin': 'models/en-fi/retrain_hr_b45LsGaNQFyDRhHAvBbKrA/exported/lex.50.50.enfi.s2t.bin.gz' } },
  fr: { model: 'model.enfr.intgemm.alphas.bin', srcVocab: 'vocab.enfr.spm', tgtVocab: 'vocab.enfr.spm', lex: 'lex.50.50.enfr.s2t.bin', paths: { 'model.enfr.intgemm.alphas.bin': 'models/en-fr/retrain_hr_NLIxDbE1TBGyOTI-zwZagw/exported/model.enfr.intgemm.alphas.bin.gz', 'vocab.enfr.spm': 'models/en-fr/retrain_hr_NLIxDbE1TBGyOTI-zwZagw/exported/vocab.enfr.spm.gz', 'vocab.enfr.spm': 'models/en-fr/retrain_hr_NLIxDbE1TBGyOTI-zwZagw/exported/vocab.enfr.spm.gz', 'lex.50.50.enfr.s2t.bin': 'models/en-fr/retrain_hr_NLIxDbE1TBGyOTI-zwZagw/exported/lex.50.50.enfr.s2t.bin.gz' } },
  gu: { model: 'model.engu.intgemm.alphas.bin', srcVocab: 'vocab.engu.spm', tgtVocab: 'vocab.engu.spm', lex: 'lex.50.50.engu.s2t.bin', paths: { 'model.engu.intgemm.alphas.bin': 'models/en-gu/h1-2025_Na2-WpCIR1Sdy17l-XDeLA/exported/model.engu.intgemm.alphas.bin.gz', 'vocab.engu.spm': 'models/en-gu/h1-2025_Na2-WpCIR1Sdy17l-XDeLA/exported/vocab.engu.spm.gz', 'vocab.engu.spm': 'models/en-gu/h1-2025_Na2-WpCIR1Sdy17l-XDeLA/exported/vocab.engu.spm.gz', 'lex.50.50.engu.s2t.bin': 'models/en-gu/h1-2025_Na2-WpCIR1Sdy17l-XDeLA/exported/lex.50.50.engu.s2t.bin.gz' } },
  he: { model: 'model.enhe.intgemm.alphas.bin', srcVocab: 'vocab.enhe.spm', tgtVocab: 'vocab.enhe.spm', lex: 'lex.50.50.enhe.s2t.bin', paths: { 'model.enhe.intgemm.alphas.bin': 'models/en-he/h1-2025_QtanzRiDRISacRVw4WzWYQ/exported/model.enhe.intgemm.alphas.bin.gz', 'vocab.enhe.spm': 'models/en-he/h1-2025_QtanzRiDRISacRVw4WzWYQ/exported/vocab.enhe.spm.gz', 'vocab.enhe.spm': 'models/en-he/h1-2025_QtanzRiDRISacRVw4WzWYQ/exported/vocab.enhe.spm.gz', 'lex.50.50.enhe.s2t.bin': 'models/en-he/h1-2025_QtanzRiDRISacRVw4WzWYQ/exported/lex.50.50.enhe.s2t.bin.gz' } },
  hi: { model: 'model.enhi.intgemm.alphas.bin', srcVocab: 'vocab.enhi.spm', tgtVocab: 'vocab.enhi.spm', lex: 'lex.50.50.enhi.s2t.bin', paths: { 'model.enhi.intgemm.alphas.bin': 'models/en-hi/h1-2025_KoJuCNf_Q42R2Bz6j2jlOQ/exported/model.enhi.intgemm.alphas.bin.gz', 'vocab.enhi.spm': 'models/en-hi/h1-2025_KoJuCNf_Q42R2Bz6j2jlOQ/exported/vocab.enhi.spm.gz', 'vocab.enhi.spm': 'models/en-hi/h1-2025_KoJuCNf_Q42R2Bz6j2jlOQ/exported/vocab.enhi.spm.gz', 'lex.50.50.enhi.s2t.bin': 'models/en-hi/h1-2025_KoJuCNf_Q42R2Bz6j2jlOQ/exported/lex.50.50.enhi.s2t.bin.gz' } },
  hr: { model: 'model.enhr.intgemm.alphas.bin', srcVocab: 'vocab.enhr.spm', tgtVocab: 'vocab.enhr.spm', lex: 'lex.50.50.enhr.s2t.bin', paths: { 'model.enhr.intgemm.alphas.bin': 'models/en-hr/hbs-topk10_PLHJ-5OxSNyWlwZM12Kghw/exported/model.enhr.intgemm.alphas.bin.gz', 'vocab.enhr.spm': 'models/en-hr/hbs-topk10_PLHJ-5OxSNyWlwZM12Kghw/exported/vocab.enhr.spm.gz', 'vocab.enhr.spm': 'models/en-hr/hbs-topk10_PLHJ-5OxSNyWlwZM12Kghw/exported/vocab.enhr.spm.gz', 'lex.50.50.enhr.s2t.bin': 'models/en-hr/hbs-topk10_PLHJ-5OxSNyWlwZM12Kghw/exported/lex.50.50.enhr.s2t.bin.gz' } },
  hu: { model: 'model.enhu.intgemm.alphas.bin', srcVocab: 'vocab.enhu.spm', tgtVocab: 'vocab.enhu.spm', lex: 'lex.50.50.enhu.s2t.bin', paths: { 'model.enhu.intgemm.alphas.bin': 'models/en-hu/h1-2025_J8_9zNmQT2GfHg7_heOI_Q/exported/model.enhu.intgemm.alphas.bin.gz', 'vocab.enhu.spm': 'models/en-hu/h1-2025_J8_9zNmQT2GfHg7_heOI_Q/exported/vocab.enhu.spm.gz', 'vocab.enhu.spm': 'models/en-hu/h1-2025_J8_9zNmQT2GfHg7_heOI_Q/exported/vocab.enhu.spm.gz', 'lex.50.50.enhu.s2t.bin': 'models/en-hu/h1-2025_J8_9zNmQT2GfHg7_heOI_Q/exported/lex.50.50.enhu.s2t.bin.gz' } },
  id: { model: 'model.enid.intgemm.alphas.bin', srcVocab: 'vocab.enid.spm', tgtVocab: 'vocab.enid.spm', lex: 'lex.50.50.enid.s2t.bin', paths: { 'model.enid.intgemm.alphas.bin': 'models/en-id/spring-2024_bbjDBFoDTNGSUo2if3ET_A/exported/model.enid.intgemm.alphas.bin.gz', 'vocab.enid.spm': 'models/en-id/spring-2024_bbjDBFoDTNGSUo2if3ET_A/exported/vocab.enid.spm.gz', 'vocab.enid.spm': 'models/en-id/spring-2024_bbjDBFoDTNGSUo2if3ET_A/exported/vocab.enid.spm.gz', 'lex.50.50.enid.s2t.bin': 'models/en-id/spring-2024_bbjDBFoDTNGSUo2if3ET_A/exported/lex.50.50.enid.s2t.bin.gz' } },
  is: { model: 'model.enis.intgemm.alphas.bin', srcVocab: 'vocab.enis.spm', tgtVocab: 'vocab.enis.spm', lex: 'lex.50.50.enis.s2t.bin', paths: { 'model.enis.intgemm.alphas.bin': 'models/en-is/docmt-vocab_EkZBaZqDS5Cce_lC2BpxlA/exported/model.enis.intgemm.alphas.bin.gz', 'vocab.enis.spm': 'models/en-is/docmt-vocab_EkZBaZqDS5Cce_lC2BpxlA/exported/vocab.enis.spm.gz', 'vocab.enis.spm': 'models/en-is/docmt-vocab_EkZBaZqDS5Cce_lC2BpxlA/exported/vocab.enis.spm.gz', 'lex.50.50.enis.s2t.bin': 'models/en-is/docmt-vocab_EkZBaZqDS5Cce_lC2BpxlA/exported/lex.50.50.enis.s2t.bin.gz' } },
  it: { model: 'model.enit.intgemm.alphas.bin', srcVocab: 'vocab.enit.spm', tgtVocab: 'vocab.enit.spm', lex: 'lex.50.50.enit.s2t.bin', paths: { 'model.enit.intgemm.alphas.bin': 'models/en-it/retrain_hr_fix_names_GPSr_u8PSmC9fOx1ZDCHoA/exported/model.enit.intgemm.alphas.bin.gz', 'vocab.enit.spm': 'models/en-it/retrain_hr_fix_names_GPSr_u8PSmC9fOx1ZDCHoA/exported/vocab.enit.spm.gz', 'vocab.enit.spm': 'models/en-it/retrain_hr_fix_names_GPSr_u8PSmC9fOx1ZDCHoA/exported/vocab.enit.spm.gz', 'lex.50.50.enit.s2t.bin': 'models/en-it/retrain_hr_fix_names_GPSr_u8PSmC9fOx1ZDCHoA/exported/lex.50.50.enit.s2t.bin.gz' } },
  ja: { model: 'model.enja.intgemm.alphas.bin', srcVocab: 'srcvocab.enja.spm', tgtVocab: 'trgvocab.enja.spm', lex: 'lex.50.50.enja.s2t.bin', paths: { 'model.enja.intgemm.alphas.bin': 'models/en-ja/llmaat_finetune10M_qe8_f2_ApiGGQIwTKuF9i_k3n9Q2Q/exported/model.enja.intgemm.alphas.bin.gz', 'srcvocab.enja.spm': 'models/en-ja/llmaat_finetune10M_qe8_f2_ApiGGQIwTKuF9i_k3n9Q2Q/exported/srcvocab.enja.spm.gz', 'trgvocab.enja.spm': 'models/en-ja/llmaat_finetune10M_qe8_f2_ApiGGQIwTKuF9i_k3n9Q2Q/exported/trgvocab.enja.spm.gz', 'lex.50.50.enja.s2t.bin': 'models/en-ja/llmaat_finetune10M_qe8_f2_ApiGGQIwTKuF9i_k3n9Q2Q/exported/lex.50.50.enja.s2t.bin.gz' } },
  kn: { model: 'model.enkn.intgemm.alphas.bin', srcVocab: 'vocab.enkn.spm', tgtVocab: 'vocab.enkn.spm', lex: 'lex.50.50.enkn.s2t.bin', paths: { 'model.enkn.intgemm.alphas.bin': 'models/en-kn/h1-2025_DDVsjRwsQ8GL3-JAiAmmfQ/exported/model.enkn.intgemm.alphas.bin.gz', 'vocab.enkn.spm': 'models/en-kn/h1-2025_DDVsjRwsQ8GL3-JAiAmmfQ/exported/vocab.enkn.spm.gz', 'vocab.enkn.spm': 'models/en-kn/h1-2025_DDVsjRwsQ8GL3-JAiAmmfQ/exported/vocab.enkn.spm.gz', 'lex.50.50.enkn.s2t.bin': 'models/en-kn/h1-2025_DDVsjRwsQ8GL3-JAiAmmfQ/exported/lex.50.50.enkn.s2t.bin.gz' } },
  ko: { model: 'model.enko.intgemm.alphas.bin', srcVocab: 'srcvocab.enko.spm', tgtVocab: 'trgvocab.enko.spm', lex: 'lex.50.50.enko.s2t.bin', paths: { 'model.enko.intgemm.alphas.bin': 'models/en-ko/cjk_retrain_base-memory_GP50C3MpQ9apCWZOW-f3PA/exported/model.enko.intgemm.alphas.bin.gz', 'srcvocab.enko.spm': 'models/en-ko/cjk_retrain_base-memory_GP50C3MpQ9apCWZOW-f3PA/exported/srcvocab.enko.spm.gz', 'trgvocab.enko.spm': 'models/en-ko/cjk_retrain_base-memory_GP50C3MpQ9apCWZOW-f3PA/exported/trgvocab.enko.spm.gz', 'lex.50.50.enko.s2t.bin': 'models/en-ko/cjk_retrain_base-memory_GP50C3MpQ9apCWZOW-f3PA/exported/lex.50.50.enko.s2t.bin.gz' } },
  lt: { model: 'model.enlt.intgemm.alphas.bin', srcVocab: 'vocab.enlt.spm', tgtVocab: 'vocab.enlt.spm', lex: 'lex.50.50.enlt.s2t.bin', paths: { 'model.enlt.intgemm.alphas.bin': 'models/en-lt/h1-2025_CpawQ31iTrmnax9Xi0DkBw/exported/model.enlt.intgemm.alphas.bin.gz', 'vocab.enlt.spm': 'models/en-lt/h1-2025_CpawQ31iTrmnax9Xi0DkBw/exported/vocab.enlt.spm.gz', 'vocab.enlt.spm': 'models/en-lt/h1-2025_CpawQ31iTrmnax9Xi0DkBw/exported/vocab.enlt.spm.gz', 'lex.50.50.enlt.s2t.bin': 'models/en-lt/h1-2025_CpawQ31iTrmnax9Xi0DkBw/exported/lex.50.50.enlt.s2t.bin.gz' } },
  lv: { model: 'model.enlv.intgemm.alphas.bin', srcVocab: 'vocab.enlv.spm', tgtVocab: 'vocab.enlv.spm', lex: 'lex.50.50.enlv.s2t.bin', paths: { 'model.enlv.intgemm.alphas.bin': 'models/en-lv/h1-2025_L9sajlF2TCKfEzDro4tK3Q/exported/model.enlv.intgemm.alphas.bin.gz', 'vocab.enlv.spm': 'models/en-lv/h1-2025_L9sajlF2TCKfEzDro4tK3Q/exported/vocab.enlv.spm.gz', 'vocab.enlv.spm': 'models/en-lv/h1-2025_L9sajlF2TCKfEzDro4tK3Q/exported/vocab.enlv.spm.gz', 'lex.50.50.enlv.s2t.bin': 'models/en-lv/h1-2025_L9sajlF2TCKfEzDro4tK3Q/exported/lex.50.50.enlv.s2t.bin.gz' } },
  ml: { model: 'model.enml.intgemm.alphas.bin', srcVocab: 'vocab.enml.spm', tgtVocab: 'vocab.enml.spm', lex: 'lex.50.50.enml.s2t.bin', paths: { 'model.enml.intgemm.alphas.bin': 'models/en-ml/h1-2025_UylcthuMRoelqd6lsCbXJw/exported/model.enml.intgemm.alphas.bin.gz', 'vocab.enml.spm': 'models/en-ml/h1-2025_UylcthuMRoelqd6lsCbXJw/exported/vocab.enml.spm.gz', 'vocab.enml.spm': 'models/en-ml/h1-2025_UylcthuMRoelqd6lsCbXJw/exported/vocab.enml.spm.gz', 'lex.50.50.enml.s2t.bin': 'models/en-ml/h1-2025_UylcthuMRoelqd6lsCbXJw/exported/lex.50.50.enml.s2t.bin.gz' } },
  ms: { model: 'model.enms.intgemm.alphas.bin', srcVocab: 'vocab.enms.spm', tgtVocab: 'vocab.enms.spm', lex: 'lex.50.50.enms.s2t.bin', paths: { 'model.enms.intgemm.alphas.bin': 'models/en-ms/h1-2025_Ba76abX1Qtums6Vbv95tzg/exported/model.enms.intgemm.alphas.bin.gz', 'vocab.enms.spm': 'models/en-ms/h1-2025_Ba76abX1Qtums6Vbv95tzg/exported/vocab.enms.spm.gz', 'vocab.enms.spm': 'models/en-ms/h1-2025_Ba76abX1Qtums6Vbv95tzg/exported/vocab.enms.spm.gz', 'lex.50.50.enms.s2t.bin': 'models/en-ms/h1-2025_Ba76abX1Qtums6Vbv95tzg/exported/lex.50.50.enms.s2t.bin.gz' } },
  nb: { model: 'model.ennb.intgemm.alphas.bin', srcVocab: 'vocab.ennb.spm', tgtVocab: 'vocab.ennb.spm', lex: 'lex.50.50.ennb.s2t.bin', paths: { 'model.ennb.intgemm.alphas.bin': 'models/en-nb/h1-2025_A0d8NsivR6Szy2dI4Nz6FQ/exported/model.ennb.intgemm.alphas.bin.gz', 'vocab.ennb.spm': 'models/en-nb/h1-2025_A0d8NsivR6Szy2dI4Nz6FQ/exported/vocab.ennb.spm.gz', 'vocab.ennb.spm': 'models/en-nb/h1-2025_A0d8NsivR6Szy2dI4Nz6FQ/exported/vocab.ennb.spm.gz', 'lex.50.50.ennb.s2t.bin': 'models/en-nb/h1-2025_A0d8NsivR6Szy2dI4Nz6FQ/exported/lex.50.50.ennb.s2t.bin.gz' } },
  nl: { model: 'model.ennl.intgemm.alphas.bin', srcVocab: 'vocab.ennl.spm', tgtVocab: 'vocab.ennl.spm', lex: 'lex.50.50.ennl.s2t.bin', paths: { 'model.ennl.intgemm.alphas.bin': 'models/en-nl/retrain_hr_fix_names_fR8XhBiBQniIbi4I_ebJ2Q/exported/model.ennl.intgemm.alphas.bin.gz', 'vocab.ennl.spm': 'models/en-nl/retrain_hr_fix_names_fR8XhBiBQniIbi4I_ebJ2Q/exported/vocab.ennl.spm.gz', 'vocab.ennl.spm': 'models/en-nl/retrain_hr_fix_names_fR8XhBiBQniIbi4I_ebJ2Q/exported/vocab.ennl.spm.gz', 'lex.50.50.ennl.s2t.bin': 'models/en-nl/retrain_hr_fix_names_fR8XhBiBQniIbi4I_ebJ2Q/exported/lex.50.50.ennl.s2t.bin.gz' } },
  no: { model: 'model.enno.intgemm.alphas.bin', srcVocab: 'vocab.enno.spm', tgtVocab: 'vocab.enno.spm', lex: 'lex.50.50.enno.s2t.bin', paths: { 'model.enno.intgemm.alphas.bin': 'models/en-no/h1-2025_A0d8NsivR6Szy2dI4Nz6FQ/exported/model.enno.intgemm.alphas.bin.gz', 'vocab.enno.spm': 'models/en-no/h1-2025_A0d8NsivR6Szy2dI4Nz6FQ/exported/vocab.enno.spm.gz', 'vocab.enno.spm': 'models/en-no/h1-2025_A0d8NsivR6Szy2dI4Nz6FQ/exported/vocab.enno.spm.gz', 'lex.50.50.enno.s2t.bin': 'models/en-no/h1-2025_A0d8NsivR6Szy2dI4Nz6FQ/exported/lex.50.50.enno.s2t.bin.gz' } },
  pl: { model: 'model.enpl.intgemm.alphas.bin', srcVocab: 'vocab.enpl.spm', tgtVocab: 'vocab.enpl.spm', lex: 'lex.50.50.enpl.s2t.bin', paths: { 'model.enpl.intgemm.alphas.bin': 'models/en-pl/retrain_hr_fix_names_YmTlfuUsSKCbUp75UXaUuw/exported/model.enpl.intgemm.alphas.bin.gz', 'vocab.enpl.spm': 'models/en-pl/retrain_hr_fix_names_YmTlfuUsSKCbUp75UXaUuw/exported/vocab.enpl.spm.gz', 'vocab.enpl.spm': 'models/en-pl/retrain_hr_fix_names_YmTlfuUsSKCbUp75UXaUuw/exported/vocab.enpl.spm.gz', 'lex.50.50.enpl.s2t.bin': 'models/en-pl/retrain_hr_fix_names_YmTlfuUsSKCbUp75UXaUuw/exported/lex.50.50.enpl.s2t.bin.gz' } },
  pt: { model: 'model.enpt.intgemm.alphas.bin', srcVocab: 'vocab.enpt.spm', tgtVocab: 'vocab.enpt.spm', lex: 'lex.50.50.enpt.s2t.bin', paths: { 'model.enpt.intgemm.alphas.bin': 'models/en-pt/retrain_hr_fix_names_Vnb0RUXTTd67hR-oLHM3eg/exported/model.enpt.intgemm.alphas.bin.gz', 'vocab.enpt.spm': 'models/en-pt/retrain_hr_fix_names_Vnb0RUXTTd67hR-oLHM3eg/exported/vocab.enpt.spm.gz', 'vocab.enpt.spm': 'models/en-pt/retrain_hr_fix_names_Vnb0RUXTTd67hR-oLHM3eg/exported/vocab.enpt.spm.gz', 'lex.50.50.enpt.s2t.bin': 'models/en-pt/retrain_hr_fix_names_Vnb0RUXTTd67hR-oLHM3eg/exported/lex.50.50.enpt.s2t.bin.gz' } },
  ro: { model: 'model.enro.intgemm.alphas.bin', srcVocab: 'vocab.enro.spm', tgtVocab: 'vocab.enro.spm', lex: 'lex.50.50.enro.s2t.bin', paths: { 'model.enro.intgemm.alphas.bin': 'models/en-ro/spring-2024_Ov3G4D_DRJa-4qTlILkPhg/exported/model.enro.intgemm.alphas.bin.gz', 'vocab.enro.spm': 'models/en-ro/spring-2024_Ov3G4D_DRJa-4qTlILkPhg/exported/vocab.enro.spm.gz', 'vocab.enro.spm': 'models/en-ro/spring-2024_Ov3G4D_DRJa-4qTlILkPhg/exported/vocab.enro.spm.gz', 'lex.50.50.enro.s2t.bin': 'models/en-ro/spring-2024_Ov3G4D_DRJa-4qTlILkPhg/exported/lex.50.50.enro.s2t.bin.gz' } },
  ru: { model: 'model.enru.intgemm.alphas.bin', srcVocab: 'vocab.enru.spm', tgtVocab: 'vocab.enru.spm', lex: 'lex.50.50.enru.s2t.bin', paths: { 'model.enru.intgemm.alphas.bin': 'models/en-ru/retrain_base-memory_KJ23-iDVTcymG1ZldWY17w/exported/model.enru.intgemm.alphas.bin.gz', 'vocab.enru.spm': 'models/en-ru/retrain_base-memory_KJ23-iDVTcymG1ZldWY17w/exported/vocab.enru.spm.gz', 'vocab.enru.spm': 'models/en-ru/retrain_base-memory_KJ23-iDVTcymG1ZldWY17w/exported/vocab.enru.spm.gz', 'lex.50.50.enru.s2t.bin': 'models/en-ru/retrain_base-memory_KJ23-iDVTcymG1ZldWY17w/exported/lex.50.50.enru.s2t.bin.gz' } },
  sk: { model: 'model.ensk.intgemm.alphas.bin', srcVocab: 'vocab.ensk.spm', tgtVocab: 'vocab.ensk.spm', lex: 'lex.50.50.ensk.s2t.bin', paths: { 'model.ensk.intgemm.alphas.bin': 'models/en-sk/h1-2025_NbGVkenLTPiss8w800509A/exported/model.ensk.intgemm.alphas.bin.gz', 'vocab.ensk.spm': 'models/en-sk/h1-2025_NbGVkenLTPiss8w800509A/exported/vocab.ensk.spm.gz', 'vocab.ensk.spm': 'models/en-sk/h1-2025_NbGVkenLTPiss8w800509A/exported/vocab.ensk.spm.gz', 'lex.50.50.ensk.s2t.bin': 'models/en-sk/h1-2025_NbGVkenLTPiss8w800509A/exported/lex.50.50.ensk.s2t.bin.gz' } },
  sl: { model: 'model.ensl.intgemm.alphas.bin', srcVocab: 'vocab.ensl.spm', tgtVocab: 'vocab.ensl.spm', lex: 'lex.50.50.ensl.s2t.bin', paths: { 'model.ensl.intgemm.alphas.bin': 'models/en-sl/h1-2025_Ph0DK4RhRMe7z4cLk-f7eg/exported/model.ensl.intgemm.alphas.bin.gz', 'vocab.ensl.spm': 'models/en-sl/h1-2025_Ph0DK4RhRMe7z4cLk-f7eg/exported/vocab.ensl.spm.gz', 'vocab.ensl.spm': 'models/en-sl/h1-2025_Ph0DK4RhRMe7z4cLk-f7eg/exported/vocab.ensl.spm.gz', 'lex.50.50.ensl.s2t.bin': 'models/en-sl/h1-2025_Ph0DK4RhRMe7z4cLk-f7eg/exported/lex.50.50.ensl.s2t.bin.gz' } },
  sq: { model: 'model.ensq.intgemm.alphas.bin', srcVocab: 'vocab.ensq.spm', tgtVocab: 'vocab.ensq.spm', lex: 'lex.50.50.ensq.s2t.bin', paths: { 'model.ensq.intgemm.alphas.bin': 'models/en-sq/h1-2025_HIreYm8_RDymI1qFdn0V5Q/exported/model.ensq.intgemm.alphas.bin.gz', 'vocab.ensq.spm': 'models/en-sq/h1-2025_HIreYm8_RDymI1qFdn0V5Q/exported/vocab.ensq.spm.gz', 'vocab.ensq.spm': 'models/en-sq/h1-2025_HIreYm8_RDymI1qFdn0V5Q/exported/vocab.ensq.spm.gz', 'lex.50.50.ensq.s2t.bin': 'models/en-sq/h1-2025_HIreYm8_RDymI1qFdn0V5Q/exported/lex.50.50.ensq.s2t.bin.gz' } },
  sr: { model: 'model.ensr.intgemm.alphas.bin', srcVocab: 'vocab.ensr.spm', tgtVocab: 'vocab.ensr.spm', lex: 'lex.50.50.ensr.s2t.bin', paths: { 'model.ensr.intgemm.alphas.bin': 'models/en-sr/hbs-topk10_KZK68xhrQWWeK6xcMRtd9A/exported/model.ensr.intgemm.alphas.bin.gz', 'vocab.ensr.spm': 'models/en-sr/hbs-topk10_KZK68xhrQWWeK6xcMRtd9A/exported/vocab.ensr.spm.gz', 'vocab.ensr.spm': 'models/en-sr/hbs-topk10_KZK68xhrQWWeK6xcMRtd9A/exported/vocab.ensr.spm.gz', 'lex.50.50.ensr.s2t.bin': 'models/en-sr/hbs-topk10_KZK68xhrQWWeK6xcMRtd9A/exported/lex.50.50.ensr.s2t.bin.gz' } },
  sv: { model: 'model.ensv.intgemm.alphas.bin', srcVocab: 'vocab.ensv.spm', tgtVocab: 'vocab.ensv.spm', lex: 'lex.50.50.ensv.s2t.bin', paths: { 'model.ensv.intgemm.alphas.bin': 'models/en-sv/spring-2024_bQQme71PS4eZRDl3NM-kgA/exported/model.ensv.intgemm.alphas.bin.gz', 'vocab.ensv.spm': 'models/en-sv/spring-2024_bQQme71PS4eZRDl3NM-kgA/exported/vocab.ensv.spm.gz', 'vocab.ensv.spm': 'models/en-sv/spring-2024_bQQme71PS4eZRDl3NM-kgA/exported/vocab.ensv.spm.gz', 'lex.50.50.ensv.s2t.bin': 'models/en-sv/spring-2024_bQQme71PS4eZRDl3NM-kgA/exported/lex.50.50.ensv.s2t.bin.gz' } },
  ta: { model: 'model.enta.intgemm.alphas.bin', srcVocab: 'vocab.enta.spm', tgtVocab: 'vocab.enta.spm', lex: 'lex.50.50.enta.s2t.bin', paths: { 'model.enta.intgemm.alphas.bin': 'models/en-ta/h1-2025_aPztISjSRums11fBuT--4A/exported/model.enta.intgemm.alphas.bin.gz', 'vocab.enta.spm': 'models/en-ta/h1-2025_aPztISjSRums11fBuT--4A/exported/vocab.enta.spm.gz', 'vocab.enta.spm': 'models/en-ta/h1-2025_aPztISjSRums11fBuT--4A/exported/vocab.enta.spm.gz', 'lex.50.50.enta.s2t.bin': 'models/en-ta/h1-2025_aPztISjSRums11fBuT--4A/exported/lex.50.50.enta.s2t.bin.gz' } },
  te: { model: 'model.ente.intgemm.alphas.bin', srcVocab: 'vocab.ente.spm', tgtVocab: 'vocab.ente.spm', lex: 'lex.50.50.ente.s2t.bin', paths: { 'model.ente.intgemm.alphas.bin': 'models/en-te/h1-2025_J_7yoPHaRJqsevUR512RsQ/exported/model.ente.intgemm.alphas.bin.gz', 'vocab.ente.spm': 'models/en-te/h1-2025_J_7yoPHaRJqsevUR512RsQ/exported/vocab.ente.spm.gz', 'vocab.ente.spm': 'models/en-te/h1-2025_J_7yoPHaRJqsevUR512RsQ/exported/vocab.ente.spm.gz', 'lex.50.50.ente.s2t.bin': 'models/en-te/h1-2025_J_7yoPHaRJqsevUR512RsQ/exported/lex.50.50.ente.s2t.bin.gz' } },
  th: { model: 'model.enth.intgemm.alphas.bin', srcVocab: 'vocab.enth.spm', tgtVocab: 'vocab.enth.spm', lex: 'lex.50.50.enth.s2t.bin', paths: { 'model.enth.intgemm.alphas.bin': 'models/en-th/new-opuscleaner-en-th-onestage-topk10_WIvJuHhrSyiXLtJBJOUrsA/exported/model.enth.intgemm.alphas.bin.gz', 'vocab.enth.spm': 'models/en-th/new-opuscleaner-en-th-onestage-topk10_WIvJuHhrSyiXLtJBJOUrsA/exported/vocab.enth.spm.gz', 'vocab.enth.spm': 'models/en-th/new-opuscleaner-en-th-onestage-topk10_WIvJuHhrSyiXLtJBJOUrsA/exported/vocab.enth.spm.gz', 'lex.50.50.enth.s2t.bin': 'models/en-th/new-opuscleaner-en-th-onestage-topk10_WIvJuHhrSyiXLtJBJOUrsA/exported/lex.50.50.enth.s2t.bin.gz' } },
  tr: { model: 'model.entr.intgemm.alphas.bin', srcVocab: 'vocab.entr.spm', tgtVocab: 'vocab.entr.spm', lex: 'lex.50.50.entr.s2t.bin', paths: { 'model.entr.intgemm.alphas.bin': 'models/en-tr/spring-2024_LiFGeNrEQpKdNlziG2qP_A/exported/model.entr.intgemm.alphas.bin.gz', 'vocab.entr.spm': 'models/en-tr/spring-2024_LiFGeNrEQpKdNlziG2qP_A/exported/vocab.entr.spm.gz', 'vocab.entr.spm': 'models/en-tr/spring-2024_LiFGeNrEQpKdNlziG2qP_A/exported/vocab.entr.spm.gz', 'lex.50.50.entr.s2t.bin': 'models/en-tr/spring-2024_LiFGeNrEQpKdNlziG2qP_A/exported/lex.50.50.entr.s2t.bin.gz' } },
  uk: { model: 'model.enuk.intgemm.alphas.bin', srcVocab: 'vocab.enuk.spm', tgtVocab: 'vocab.enuk.spm', lex: 'lex.50.50.enuk.s2t.bin', paths: { 'model.enuk.intgemm.alphas.bin': 'models/en-uk/docmt-vocab_a2OVwdI-Sg-SBZ_0Joqb0w/exported/model.enuk.intgemm.alphas.bin.gz', 'vocab.enuk.spm': 'models/en-uk/docmt-vocab_a2OVwdI-Sg-SBZ_0Joqb0w/exported/vocab.enuk.spm.gz', 'vocab.enuk.spm': 'models/en-uk/docmt-vocab_a2OVwdI-Sg-SBZ_0Joqb0w/exported/vocab.enuk.spm.gz', 'lex.50.50.enuk.s2t.bin': 'models/en-uk/docmt-vocab_a2OVwdI-Sg-SBZ_0Joqb0w/exported/lex.50.50.enuk.s2t.bin.gz' } },
  vi: { model: 'model.envi.intgemm.alphas.bin', srcVocab: 'vocab.envi.spm', tgtVocab: 'vocab.envi.spm', lex: 'lex.50.50.envi.s2t.bin', paths: { 'model.envi.intgemm.alphas.bin': 'models/en-vi/test_prompsit_Ep8JhBQ3QRizDT91JVy8KQ/exported/model.envi.intgemm.alphas.bin.gz', 'vocab.envi.spm': 'models/en-vi/test_prompsit_Ep8JhBQ3QRizDT91JVy8KQ/exported/vocab.envi.spm.gz', 'vocab.envi.spm': 'models/en-vi/test_prompsit_Ep8JhBQ3QRizDT91JVy8KQ/exported/vocab.envi.spm.gz', 'lex.50.50.envi.s2t.bin': 'models/en-vi/test_prompsit_Ep8JhBQ3QRizDT91JVy8KQ/exported/lex.50.50.envi.s2t.bin.gz' } },
  zh: { model: 'model.enzh.intgemm.alphas.bin', srcVocab: 'srcvocab.enzh.spm', tgtVocab: 'trgvocab.enzh.spm', lex: 'lex.50.50.enzh.s2t.bin', paths: { 'model.enzh.intgemm.alphas.bin': 'models/en-zh/llmaat_finetune10M_qe8_f2_ByQcSxGXQRqGi-UTxYE43g/exported/model.enzh.intgemm.alphas.bin.gz', 'srcvocab.enzh.spm': 'models/en-zh/llmaat_finetune10M_qe8_f2_ByQcSxGXQRqGi-UTxYE43g/exported/srcvocab.enzh.spm.gz', 'trgvocab.enzh.spm': 'models/en-zh/llmaat_finetune10M_qe8_f2_ByQcSxGXQRqGi-UTxYE43g/exported/trgvocab.enzh.spm.gz', 'lex.50.50.enzh.s2t.bin': 'models/en-zh/llmaat_finetune10M_qe8_f2_ByQcSxGXQRqGi-UTxYE43g/exported/lex.50.50.enzh.s2t.bin.gz' } },
  zh_hant: { model: 'model.enzh_hant.intgemm.alphas.bin', srcVocab: 'srcvocab.enzh_hant.spm', tgtVocab: 'trgvocab.enzh_hant.spm', lex: 'lex.50.50.enzh_hant.s2t.bin', paths: { 'model.enzh_hant.intgemm.alphas.bin': 'models/en-zh_hant/zh_hant_llmaat_finetune10M_qe8_f2_aQ8azdOMQOSBVjBDOVDIZQ/exported/model.enzh_hant.intgemm.alphas.bin.gz', 'srcvocab.enzh_hant.spm': 'models/en-zh_hant/zh_hant_llmaat_finetune10M_qe8_f2_aQ8azdOMQOSBVjBDOVDIZQ/exported/srcvocab.enzh_hant.spm.gz', 'trgvocab.enzh_hant.spm': 'models/en-zh_hant/zh_hant_llmaat_finetune10M_qe8_f2_aQ8azdOMQOSBVjBDOVDIZQ/exported/trgvocab.enzh_hant.spm.gz', 'lex.50.50.enzh_hant.s2t.bin': 'models/en-zh_hant/zh_hant_llmaat_finetune10M_qe8_f2_aQ8azdOMQOSBVjBDOVDIZQ/exported/lex.50.50.enzh_hant.s2t.bin.gz' } },
};

// toEnglishFiles: lang -> en
const TO_ENGLISH = {
  ar: { model: 'model.aren.intgemm.alphas.bin', srcVocab: 'vocab.aren.spm', tgtVocab: 'vocab.aren.spm', lex: 'lex.50.50.aren.s2t.bin', paths: { 'model.aren.intgemm.alphas.bin': 'models/ar-en/retrain_base-memory_X9fDxFreTOCslPKzb1CXTg/exported/model.aren.intgemm.alphas.bin.gz', 'vocab.aren.spm': 'models/ar-en/retrain_base-memory_X9fDxFreTOCslPKzb1CXTg/exported/vocab.aren.spm.gz', 'vocab.aren.spm': 'models/ar-en/retrain_base-memory_X9fDxFreTOCslPKzb1CXTg/exported/vocab.aren.spm.gz', 'lex.50.50.aren.s2t.bin': 'models/ar-en/retrain_base-memory_X9fDxFreTOCslPKzb1CXTg/exported/lex.50.50.aren.s2t.bin.gz' } },
  az: { model: 'model.azen.intgemm.alphas.bin', srcVocab: 'vocab.azen.spm', tgtVocab: 'vocab.azen.spm', lex: 'lex.50.50.azen.s2t.bin', paths: { 'model.azen.intgemm.alphas.bin': 'models/az-en/h1-2025_Tm4nvtoLQnakAWSGhBZ-eA/exported/model.azen.intgemm.alphas.bin.gz', 'vocab.azen.spm': 'models/az-en/h1-2025_Tm4nvtoLQnakAWSGhBZ-eA/exported/vocab.azen.spm.gz', 'vocab.azen.spm': 'models/az-en/h1-2025_Tm4nvtoLQnakAWSGhBZ-eA/exported/vocab.azen.spm.gz', 'lex.50.50.azen.s2t.bin': 'models/az-en/h1-2025_Tm4nvtoLQnakAWSGhBZ-eA/exported/lex.50.50.azen.s2t.bin.gz' } },
  be: { model: 'model.been.intgemm.alphas.bin', srcVocab: 'vocab.been.spm', tgtVocab: 'vocab.been.spm', lex: 'lex.50.50.been.s2t.bin', paths: { 'model.been.intgemm.alphas.bin': 'models/be-en/h1-2025_ARgOSPOSRVmOWTwFvRVOjA/exported/model.been.intgemm.alphas.bin.gz', 'vocab.been.spm': 'models/be-en/h1-2025_ARgOSPOSRVmOWTwFvRVOjA/exported/vocab.been.spm.gz', 'vocab.been.spm': 'models/be-en/h1-2025_ARgOSPOSRVmOWTwFvRVOjA/exported/vocab.been.spm.gz', 'lex.50.50.been.s2t.bin': 'models/be-en/h1-2025_ARgOSPOSRVmOWTwFvRVOjA/exported/lex.50.50.been.s2t.bin.gz' } },
  bg: { model: 'model.bgen.intgemm.alphas.bin', srcVocab: 'vocab.bgen.spm', tgtVocab: 'vocab.bgen.spm', lex: 'lex.50.50.bgen.s2t.bin', paths: { 'model.bgen.intgemm.alphas.bin': 'models/bg-en/retrain_hr_WvwHu4k6TgmJ2YTvL4Mu2g/exported/model.bgen.intgemm.alphas.bin.gz', 'vocab.bgen.spm': 'models/bg-en/retrain_hr_WvwHu4k6TgmJ2YTvL4Mu2g/exported/vocab.bgen.spm.gz', 'vocab.bgen.spm': 'models/bg-en/retrain_hr_WvwHu4k6TgmJ2YTvL4Mu2g/exported/vocab.bgen.spm.gz', 'lex.50.50.bgen.s2t.bin': 'models/bg-en/retrain_hr_WvwHu4k6TgmJ2YTvL4Mu2g/exported/lex.50.50.bgen.s2t.bin.gz' } },
  bn: { model: 'model.bnen.intgemm.alphas.bin', srcVocab: 'vocab.bnen.spm', tgtVocab: 'vocab.bnen.spm', lex: 'lex.50.50.bnen.s2t.bin', paths: { 'model.bnen.intgemm.alphas.bin': 'models/bn-en/h1-2025_XcpBlhA1SyOJCH2UzoIMyQ/exported/model.bnen.intgemm.alphas.bin.gz', 'vocab.bnen.spm': 'models/bn-en/h1-2025_XcpBlhA1SyOJCH2UzoIMyQ/exported/vocab.bnen.spm.gz', 'vocab.bnen.spm': 'models/bn-en/h1-2025_XcpBlhA1SyOJCH2UzoIMyQ/exported/vocab.bnen.spm.gz', 'lex.50.50.bnen.s2t.bin': 'models/bn-en/h1-2025_XcpBlhA1SyOJCH2UzoIMyQ/exported/lex.50.50.bnen.s2t.bin.gz' } },
  bs: { model: 'model.bsen.intgemm.alphas.bin', srcVocab: 'vocab.bsen.spm', tgtVocab: 'vocab.bsen.spm', lex: 'lex.50.50.bsen.s2t.bin', paths: { 'model.bsen.intgemm.alphas.bin': 'models/bs-en/spring-2024_ArlZLOUDTlqbe5WcnWGt_A/exported/model.bsen.intgemm.alphas.bin.gz', 'vocab.bsen.spm': 'models/bs-en/spring-2024_ArlZLOUDTlqbe5WcnWGt_A/exported/vocab.bsen.spm.gz', 'vocab.bsen.spm': 'models/bs-en/spring-2024_ArlZLOUDTlqbe5WcnWGt_A/exported/vocab.bsen.spm.gz', 'lex.50.50.bsen.s2t.bin': 'models/bs-en/spring-2024_ArlZLOUDTlqbe5WcnWGt_A/exported/lex.50.50.bsen.s2t.bin.gz' } },
  ca: { model: 'model.caen.intgemm.alphas.bin', srcVocab: 'vocab.caen.spm', tgtVocab: 'vocab.caen.spm', lex: 'lex.50.50.caen.s2t.bin', paths: { 'model.caen.intgemm.alphas.bin': 'models/ca-en/target-side-dedup_xxxxxxxxRxSxxxxxxxxxxA/exported/model.caen.intgemm.alphas.bin.gz', 'vocab.caen.spm': 'models/ca-en/target-side-dedup_xxxxxxxxRxSxxxxxxxxxxA/exported/vocab.caen.spm.gz', 'vocab.caen.spm': 'models/ca-en/target-side-dedup_xxxxxxxxRxSxxxxxxxxxxA/exported/vocab.caen.spm.gz', 'lex.50.50.caen.s2t.bin': 'models/ca-en/target-side-dedup_xxxxxxxxRxSxxxxxxxxxxA/exported/lex.50.50.caen.s2t.bin.gz' } },
  cs: { model: 'model.csen.intgemm.alphas.bin', srcVocab: 'vocab.csen.spm', tgtVocab: 'vocab.csen.spm', lex: 'lex.50.50.csen.s2t.bin', paths: { 'model.csen.intgemm.alphas.bin': 'models/cs-en/retrain_hr_EwWhUov8TP6D_oolATvbUA/exported/model.csen.intgemm.alphas.bin.gz', 'vocab.csen.spm': 'models/cs-en/retrain_hr_EwWhUov8TP6D_oolATvbUA/exported/vocab.csen.spm.gz', 'vocab.csen.spm': 'models/cs-en/retrain_hr_EwWhUov8TP6D_oolATvbUA/exported/vocab.csen.spm.gz', 'lex.50.50.csen.s2t.bin': 'models/cs-en/retrain_hr_EwWhUov8TP6D_oolATvbUA/exported/lex.50.50.csen.s2t.bin.gz' } },
  da: { model: 'model.daen.intgemm.alphas.bin', srcVocab: 'vocab.daen.spm', tgtVocab: 'vocab.daen.spm', lex: 'lex.50.50.daen.s2t.bin', paths: { 'model.daen.intgemm.alphas.bin': 'models/da-en/spring-2024_U1vVpsWWT-K4L9pRfP1K1g/exported/model.daen.intgemm.alphas.bin.gz', 'vocab.daen.spm': 'models/da-en/spring-2024_U1vVpsWWT-K4L9pRfP1K1g/exported/vocab.daen.spm.gz', 'vocab.daen.spm': 'models/da-en/spring-2024_U1vVpsWWT-K4L9pRfP1K1g/exported/vocab.daen.spm.gz', 'lex.50.50.daen.s2t.bin': 'models/da-en/spring-2024_U1vVpsWWT-K4L9pRfP1K1g/exported/lex.50.50.daen.s2t.bin.gz' } },
  de: { model: 'model.deen.intgemm.alphas.bin', srcVocab: 'vocab.deen.spm', tgtVocab: 'vocab.deen.spm', lex: 'lex.50.50.deen.s2t.bin', paths: { 'model.deen.intgemm.alphas.bin': 'models/de-en/retrain_hr2_WZOW24i4QJmIib61LeHfwg/exported/model.deen.intgemm.alphas.bin.gz', 'vocab.deen.spm': 'models/de-en/retrain_hr2_WZOW24i4QJmIib61LeHfwg/exported/vocab.deen.spm.gz', 'vocab.deen.spm': 'models/de-en/retrain_hr2_WZOW24i4QJmIib61LeHfwg/exported/vocab.deen.spm.gz', 'lex.50.50.deen.s2t.bin': 'models/de-en/retrain_hr2_WZOW24i4QJmIib61LeHfwg/exported/lex.50.50.deen.s2t.bin.gz' } },
  el: { model: 'model.elen.intgemm.alphas.bin', srcVocab: 'vocab.elen.spm', tgtVocab: 'vocab.elen.spm', lex: 'lex.50.50.elen.s2t.bin', paths: { 'model.elen.intgemm.alphas.bin': 'models/el-en/spring-2024_RJucgx7LRMKB9E4oSSzdtA/exported/model.elen.intgemm.alphas.bin.gz', 'vocab.elen.spm': 'models/el-en/spring-2024_RJucgx7LRMKB9E4oSSzdtA/exported/vocab.elen.spm.gz', 'vocab.elen.spm': 'models/el-en/spring-2024_RJucgx7LRMKB9E4oSSzdtA/exported/vocab.elen.spm.gz', 'lex.50.50.elen.s2t.bin': 'models/el-en/spring-2024_RJucgx7LRMKB9E4oSSzdtA/exported/lex.50.50.elen.s2t.bin.gz' } },
  es: { model: 'model.esen.intgemm.alphas.bin', srcVocab: 'vocab.esen.spm', tgtVocab: 'vocab.esen.spm', lex: 'lex.50.50.esen.s2t.bin', paths: { 'model.esen.intgemm.alphas.bin': 'models/es-en/retrain_hr_HbNjJ60BTwmVTbhfFxuduA/exported/model.esen.intgemm.alphas.bin.gz', 'vocab.esen.spm': 'models/es-en/retrain_hr_HbNjJ60BTwmVTbhfFxuduA/exported/vocab.esen.spm.gz', 'vocab.esen.spm': 'models/es-en/retrain_hr_HbNjJ60BTwmVTbhfFxuduA/exported/vocab.esen.spm.gz', 'lex.50.50.esen.s2t.bin': 'models/es-en/retrain_hr_HbNjJ60BTwmVTbhfFxuduA/exported/lex.50.50.esen.s2t.bin.gz' } },
  et: { model: 'model.eten.intgemm.alphas.bin', srcVocab: 'vocab.eten.spm', tgtVocab: 'vocab.eten.spm', lex: 'lex.50.50.eten.s2t.bin', paths: { 'model.eten.intgemm.alphas.bin': 'models/et-en/retrain_hr_RNXxp-Q9Q4GRExCoMAT77Q/exported/model.eten.intgemm.alphas.bin.gz', 'vocab.eten.spm': 'models/et-en/retrain_hr_RNXxp-Q9Q4GRExCoMAT77Q/exported/vocab.eten.spm.gz', 'vocab.eten.spm': 'models/et-en/retrain_hr_RNXxp-Q9Q4GRExCoMAT77Q/exported/vocab.eten.spm.gz', 'lex.50.50.eten.s2t.bin': 'models/et-en/retrain_hr_RNXxp-Q9Q4GRExCoMAT77Q/exported/lex.50.50.eten.s2t.bin.gz' } },
  fa: { model: 'model.faen.intgemm.alphas.bin', srcVocab: 'vocab.faen.spm', tgtVocab: 'vocab.faen.spm', lex: 'lex.50.50.faen.s2t.bin', paths: { 'model.faen.intgemm.alphas.bin': 'models/fa-en/h1-2025_dyvKzoMQToKWHx7bbP-TtQ/exported/model.faen.intgemm.alphas.bin.gz', 'vocab.faen.spm': 'models/fa-en/h1-2025_dyvKzoMQToKWHx7bbP-TtQ/exported/vocab.faen.spm.gz', 'vocab.faen.spm': 'models/fa-en/h1-2025_dyvKzoMQToKWHx7bbP-TtQ/exported/vocab.faen.spm.gz', 'lex.50.50.faen.s2t.bin': 'models/fa-en/h1-2025_dyvKzoMQToKWHx7bbP-TtQ/exported/lex.50.50.faen.s2t.bin.gz' } },
  fi: { model: 'model.fien.intgemm.alphas.bin', srcVocab: 'vocab.fien.spm', tgtVocab: 'vocab.fien.spm', lex: 'lex.50.50.fien.s2t.bin', paths: { 'model.fien.intgemm.alphas.bin': 'models/fi-en/retrain_hr_C7-zSzS7Tm6zkOfVP7k0Gw/exported/model.fien.intgemm.alphas.bin.gz', 'vocab.fien.spm': 'models/fi-en/retrain_hr_C7-zSzS7Tm6zkOfVP7k0Gw/exported/vocab.fien.spm.gz', 'vocab.fien.spm': 'models/fi-en/retrain_hr_C7-zSzS7Tm6zkOfVP7k0Gw/exported/vocab.fien.spm.gz', 'lex.50.50.fien.s2t.bin': 'models/fi-en/retrain_hr_C7-zSzS7Tm6zkOfVP7k0Gw/exported/lex.50.50.fien.s2t.bin.gz' } },
  fr: { model: 'model.fren.intgemm.alphas.bin', srcVocab: 'vocab.fren.spm', tgtVocab: 'vocab.fren.spm', lex: 'lex.50.50.fren.s2t.bin', paths: { 'model.fren.intgemm.alphas.bin': 'models/fr-en/retrain_hr_EFgIftH_RrCyzl5gjemVNg/exported/model.fren.intgemm.alphas.bin.gz', 'vocab.fren.spm': 'models/fr-en/retrain_hr_EFgIftH_RrCyzl5gjemVNg/exported/vocab.fren.spm.gz', 'vocab.fren.spm': 'models/fr-en/retrain_hr_EFgIftH_RrCyzl5gjemVNg/exported/vocab.fren.spm.gz', 'lex.50.50.fren.s2t.bin': 'models/fr-en/retrain_hr_EFgIftH_RrCyzl5gjemVNg/exported/lex.50.50.fren.s2t.bin.gz' } },
  gu: { model: 'model.guen.intgemm.alphas.bin', srcVocab: 'vocab.guen.spm', tgtVocab: 'vocab.guen.spm', lex: 'lex.50.50.guen.s2t.bin', paths: { 'model.guen.intgemm.alphas.bin': 'models/gu-en/h1-2025_AbHCTUgSSguJ1-Pq-XLnVA/exported/model.guen.intgemm.alphas.bin.gz', 'vocab.guen.spm': 'models/gu-en/h1-2025_AbHCTUgSSguJ1-Pq-XLnVA/exported/vocab.guen.spm.gz', 'vocab.guen.spm': 'models/gu-en/h1-2025_AbHCTUgSSguJ1-Pq-XLnVA/exported/vocab.guen.spm.gz', 'lex.50.50.guen.s2t.bin': 'models/gu-en/h1-2025_AbHCTUgSSguJ1-Pq-XLnVA/exported/lex.50.50.guen.s2t.bin.gz' } },
  he: { model: 'model.heen.intgemm.alphas.bin', srcVocab: 'vocab.heen.spm', tgtVocab: 'vocab.heen.spm', lex: 'lex.50.50.heen.s2t.bin', paths: { 'model.heen.intgemm.alphas.bin': 'models/he-en/h1-2025_IZKPrf3xQaKu56F3zmH0cw/exported/model.heen.intgemm.alphas.bin.gz', 'vocab.heen.spm': 'models/he-en/h1-2025_IZKPrf3xQaKu56F3zmH0cw/exported/vocab.heen.spm.gz', 'vocab.heen.spm': 'models/he-en/h1-2025_IZKPrf3xQaKu56F3zmH0cw/exported/vocab.heen.spm.gz', 'lex.50.50.heen.s2t.bin': 'models/he-en/h1-2025_IZKPrf3xQaKu56F3zmH0cw/exported/lex.50.50.heen.s2t.bin.gz' } },
  hi: { model: 'model.hien.intgemm.alphas.bin', srcVocab: 'vocab.hien.spm', tgtVocab: 'vocab.hien.spm', lex: 'lex.50.50.hien.s2t.bin', paths: { 'model.hien.intgemm.alphas.bin': 'models/hi-en/h1-2025_IcUQD-GbSJWB6WV08oDoEw/exported/model.hien.intgemm.alphas.bin.gz', 'vocab.hien.spm': 'models/hi-en/h1-2025_IcUQD-GbSJWB6WV08oDoEw/exported/vocab.hien.spm.gz', 'vocab.hien.spm': 'models/hi-en/h1-2025_IcUQD-GbSJWB6WV08oDoEw/exported/vocab.hien.spm.gz', 'lex.50.50.hien.s2t.bin': 'models/hi-en/h1-2025_IcUQD-GbSJWB6WV08oDoEw/exported/lex.50.50.hien.s2t.bin.gz' } },
  hr: { model: 'model.hren.intgemm.alphas.bin', srcVocab: 'vocab.hren.spm', tgtVocab: 'vocab.hren.spm', lex: 'lex.50.50.hren.s2t.bin', paths: { 'model.hren.intgemm.alphas.bin': 'models/hr-en/spring-2024_eIcYjCedS26HE07kVyt5Qw/exported/model.hren.intgemm.alphas.bin.gz', 'vocab.hren.spm': 'models/hr-en/spring-2024_eIcYjCedS26HE07kVyt5Qw/exported/vocab.hren.spm.gz', 'vocab.hren.spm': 'models/hr-en/spring-2024_eIcYjCedS26HE07kVyt5Qw/exported/vocab.hren.spm.gz', 'lex.50.50.hren.s2t.bin': 'models/hr-en/spring-2024_eIcYjCedS26HE07kVyt5Qw/exported/lex.50.50.hren.s2t.bin.gz' } },
  hu: { model: 'model.huen.intgemm.alphas.bin', srcVocab: 'vocab.huen.spm', tgtVocab: 'vocab.huen.spm', lex: 'lex.50.50.huen.s2t.bin', paths: { 'model.huen.intgemm.alphas.bin': 'models/hu-en/andre_xxxxxxxxRxSxxxxxxxxxxA/exported/model.huen.intgemm.alphas.bin.gz', 'vocab.huen.spm': 'models/hu-en/andre_xxxxxxxxRxSxxxxxxxxxxA/exported/vocab.huen.spm.gz', 'vocab.huen.spm': 'models/hu-en/andre_xxxxxxxxRxSxxxxxxxxxxA/exported/vocab.huen.spm.gz', 'lex.50.50.huen.s2t.bin': 'models/hu-en/andre_xxxxxxxxRxSxxxxxxxxxxA/exported/lex.50.50.huen.s2t.bin.gz' } },
  id: { model: 'model.iden.intgemm.alphas.bin', srcVocab: 'vocab.iden.spm', tgtVocab: 'vocab.iden.spm', lex: 'lex.50.50.iden.s2t.bin', paths: { 'model.iden.intgemm.alphas.bin': 'models/id-en/spring-2024_Yl0wXq-iQE6G9PpA3AQfcg/exported/model.iden.intgemm.alphas.bin.gz', 'vocab.iden.spm': 'models/id-en/spring-2024_Yl0wXq-iQE6G9PpA3AQfcg/exported/vocab.iden.spm.gz', 'vocab.iden.spm': 'models/id-en/spring-2024_Yl0wXq-iQE6G9PpA3AQfcg/exported/vocab.iden.spm.gz', 'lex.50.50.iden.s2t.bin': 'models/id-en/spring-2024_Yl0wXq-iQE6G9PpA3AQfcg/exported/lex.50.50.iden.s2t.bin.gz' } },
  is: { model: 'model.isen.intgemm.alphas.bin', srcVocab: 'vocab.isen.spm', tgtVocab: 'vocab.isen.spm', lex: 'lex.50.50.isen.s2t.bin', paths: { 'model.isen.intgemm.alphas.bin': 'models/is-en/docmt-vocab_I4Fy2MnOQHSOT4SYlCjPWw/exported/model.isen.intgemm.alphas.bin.gz', 'vocab.isen.spm': 'models/is-en/docmt-vocab_I4Fy2MnOQHSOT4SYlCjPWw/exported/vocab.isen.spm.gz', 'vocab.isen.spm': 'models/is-en/docmt-vocab_I4Fy2MnOQHSOT4SYlCjPWw/exported/vocab.isen.spm.gz', 'lex.50.50.isen.s2t.bin': 'models/is-en/docmt-vocab_I4Fy2MnOQHSOT4SYlCjPWw/exported/lex.50.50.isen.s2t.bin.gz' } },
  it: { model: 'model.iten.intgemm.alphas.bin', srcVocab: 'vocab.iten.spm', tgtVocab: 'vocab.iten.spm', lex: 'lex.50.50.iten.s2t.bin', paths: { 'model.iten.intgemm.alphas.bin': 'models/it-en/retrain_hr_d1nPDwVeSD6t-HdtWA4xNg/exported/model.iten.intgemm.alphas.bin.gz', 'vocab.iten.spm': 'models/it-en/retrain_hr_d1nPDwVeSD6t-HdtWA4xNg/exported/vocab.iten.spm.gz', 'vocab.iten.spm': 'models/it-en/retrain_hr_d1nPDwVeSD6t-HdtWA4xNg/exported/vocab.iten.spm.gz', 'lex.50.50.iten.s2t.bin': 'models/it-en/retrain_hr_d1nPDwVeSD6t-HdtWA4xNg/exported/lex.50.50.iten.s2t.bin.gz' } },
  ja: { model: 'model.jaen.intgemm.alphas.bin', srcVocab: 'vocab.jaen.spm', tgtVocab: 'vocab.jaen.spm', lex: 'lex.50.50.jaen.s2t.bin', paths: { 'model.jaen.intgemm.alphas.bin': 'models/ja-en/cjk_retrain_base-memory_NLRJLD_pQFyrvgKtbie2nA/exported/model.jaen.intgemm.alphas.bin.gz', 'vocab.jaen.spm': 'models/ja-en/cjk_retrain_base-memory_NLRJLD_pQFyrvgKtbie2nA/exported/vocab.jaen.spm.gz', 'vocab.jaen.spm': 'models/ja-en/cjk_retrain_base-memory_NLRJLD_pQFyrvgKtbie2nA/exported/vocab.jaen.spm.gz', 'lex.50.50.jaen.s2t.bin': 'models/ja-en/cjk_retrain_base-memory_NLRJLD_pQFyrvgKtbie2nA/exported/lex.50.50.jaen.s2t.bin.gz' } },
  kn: { model: 'model.knen.intgemm.alphas.bin', srcVocab: 'vocab.knen.spm', tgtVocab: 'vocab.knen.spm', lex: 'lex.50.50.knen.s2t.bin', paths: { 'model.knen.intgemm.alphas.bin': 'models/kn-en/h1-2025_Ql24XjW0Sp-zWsmLrV5TGQ/exported/model.knen.intgemm.alphas.bin.gz', 'vocab.knen.spm': 'models/kn-en/h1-2025_Ql24XjW0Sp-zWsmLrV5TGQ/exported/vocab.knen.spm.gz', 'vocab.knen.spm': 'models/kn-en/h1-2025_Ql24XjW0Sp-zWsmLrV5TGQ/exported/vocab.knen.spm.gz', 'lex.50.50.knen.s2t.bin': 'models/kn-en/h1-2025_Ql24XjW0Sp-zWsmLrV5TGQ/exported/lex.50.50.knen.s2t.bin.gz' } },
  ko: { model: 'model.koen.intgemm.alphas.bin', srcVocab: 'vocab.koen.spm', tgtVocab: 'vocab.koen.spm', lex: 'lex.50.50.koen.s2t.bin', paths: { 'model.koen.intgemm.alphas.bin': 'models/ko-en/cjk_retrain_base-memory_QgYNtG3BTzKBFSV1wl06Pg/exported/model.koen.intgemm.alphas.bin.gz', 'vocab.koen.spm': 'models/ko-en/cjk_retrain_base-memory_QgYNtG3BTzKBFSV1wl06Pg/exported/vocab.koen.spm.gz', 'vocab.koen.spm': 'models/ko-en/cjk_retrain_base-memory_QgYNtG3BTzKBFSV1wl06Pg/exported/vocab.koen.spm.gz', 'lex.50.50.koen.s2t.bin': 'models/ko-en/cjk_retrain_base-memory_QgYNtG3BTzKBFSV1wl06Pg/exported/lex.50.50.koen.s2t.bin.gz' } },
  lt: { model: 'model.lten.intgemm.alphas.bin', srcVocab: 'vocab.lten.spm', tgtVocab: 'vocab.lten.spm', lex: 'lex.50.50.lten.s2t.bin', paths: { 'model.lten.intgemm.alphas.bin': 'models/lt-en/spring-2024_aAroslw9Ru-c5cam6SvLBg/exported/model.lten.intgemm.alphas.bin.gz', 'vocab.lten.spm': 'models/lt-en/spring-2024_aAroslw9Ru-c5cam6SvLBg/exported/vocab.lten.spm.gz', 'vocab.lten.spm': 'models/lt-en/spring-2024_aAroslw9Ru-c5cam6SvLBg/exported/vocab.lten.spm.gz', 'lex.50.50.lten.s2t.bin': 'models/lt-en/spring-2024_aAroslw9Ru-c5cam6SvLBg/exported/lex.50.50.lten.s2t.bin.gz' } },
  lv: { model: 'model.lven.intgemm.alphas.bin', srcVocab: 'vocab.lven.spm', tgtVocab: 'vocab.lven.spm', lex: 'lex.50.50.lven.s2t.bin', paths: { 'model.lven.intgemm.alphas.bin': 'models/lv-en/spring-2024_fkUrjGNcQiWrTQ5BcYbkgg/exported/model.lven.intgemm.alphas.bin.gz', 'vocab.lven.spm': 'models/lv-en/spring-2024_fkUrjGNcQiWrTQ5BcYbkgg/exported/vocab.lven.spm.gz', 'vocab.lven.spm': 'models/lv-en/spring-2024_fkUrjGNcQiWrTQ5BcYbkgg/exported/vocab.lven.spm.gz', 'lex.50.50.lven.s2t.bin': 'models/lv-en/spring-2024_fkUrjGNcQiWrTQ5BcYbkgg/exported/lex.50.50.lven.s2t.bin.gz' } },
  ml: { model: 'model.mlen.intgemm.alphas.bin', srcVocab: 'vocab.mlen.spm', tgtVocab: 'vocab.mlen.spm', lex: 'lex.50.50.mlen.s2t.bin', paths: { 'model.mlen.intgemm.alphas.bin': 'models/ml-en/h1-2025_Ahkzk6jNTAut7rz6laKkGQ/exported/model.mlen.intgemm.alphas.bin.gz', 'vocab.mlen.spm': 'models/ml-en/h1-2025_Ahkzk6jNTAut7rz6laKkGQ/exported/vocab.mlen.spm.gz', 'vocab.mlen.spm': 'models/ml-en/h1-2025_Ahkzk6jNTAut7rz6laKkGQ/exported/vocab.mlen.spm.gz', 'lex.50.50.mlen.s2t.bin': 'models/ml-en/h1-2025_Ahkzk6jNTAut7rz6laKkGQ/exported/lex.50.50.mlen.s2t.bin.gz' } },
  ms: { model: 'model.msen.intgemm.alphas.bin', srcVocab: 'vocab.msen.spm', tgtVocab: 'vocab.msen.spm', lex: 'lex.50.50.msen.s2t.bin', paths: { 'model.msen.intgemm.alphas.bin': 'models/ms-en/h1-2025_afzwIUAqQRWx5PtvozOHnw/exported/model.msen.intgemm.alphas.bin.gz', 'vocab.msen.spm': 'models/ms-en/h1-2025_afzwIUAqQRWx5PtvozOHnw/exported/vocab.msen.spm.gz', 'vocab.msen.spm': 'models/ms-en/h1-2025_afzwIUAqQRWx5PtvozOHnw/exported/vocab.msen.spm.gz', 'lex.50.50.msen.s2t.bin': 'models/ms-en/h1-2025_afzwIUAqQRWx5PtvozOHnw/exported/lex.50.50.msen.s2t.bin.gz' } },
  nb: { model: 'model.nben.intgemm.alphas.bin', srcVocab: 'vocab.nben.spm', tgtVocab: 'vocab.nben.spm', lex: 'lex.50.50.nben.s2t.bin', paths: { 'model.nben.intgemm.alphas.bin': 'models/nb-en/h1-2025_YKogHXi6Q4es3P7fEWEaBw/exported/model.nben.intgemm.alphas.bin.gz', 'vocab.nben.spm': 'models/nb-en/h1-2025_YKogHXi6Q4es3P7fEWEaBw/exported/vocab.nben.spm.gz', 'vocab.nben.spm': 'models/nb-en/h1-2025_YKogHXi6Q4es3P7fEWEaBw/exported/vocab.nben.spm.gz', 'lex.50.50.nben.s2t.bin': 'models/nb-en/h1-2025_YKogHXi6Q4es3P7fEWEaBw/exported/lex.50.50.nben.s2t.bin.gz' } },
  nl: { model: 'model.nlen.intgemm.alphas.bin', srcVocab: 'vocab.nlen.spm', tgtVocab: 'vocab.nlen.spm', lex: 'lex.50.50.nlen.s2t.bin', paths: { 'model.nlen.intgemm.alphas.bin': 'models/nl-en/retrain_hr_JbTCb42HREGvK8d6aOCjFQ/exported/model.nlen.intgemm.alphas.bin.gz', 'vocab.nlen.spm': 'models/nl-en/retrain_hr_JbTCb42HREGvK8d6aOCjFQ/exported/vocab.nlen.spm.gz', 'vocab.nlen.spm': 'models/nl-en/retrain_hr_JbTCb42HREGvK8d6aOCjFQ/exported/vocab.nlen.spm.gz', 'lex.50.50.nlen.s2t.bin': 'models/nl-en/retrain_hr_JbTCb42HREGvK8d6aOCjFQ/exported/lex.50.50.nlen.s2t.bin.gz' } },
  nn: { model: 'model.nnen.intgemm.alphas.bin', srcVocab: 'vocab.nnen.spm', tgtVocab: 'vocab.nnen.spm', lex: 'lex.50.50.nnen.s2t.bin', paths: { 'model.nnen.intgemm.alphas.bin': 'models/nn-en/statmt_xxxxxxxxRxSxxxxxxxxxxA/exported/model.nnen.intgemm.alphas.bin.gz', 'vocab.nnen.spm': 'models/nn-en/statmt_xxxxxxxxRxSxxxxxxxxxxA/exported/vocab.nnen.spm.gz', 'vocab.nnen.spm': 'models/nn-en/statmt_xxxxxxxxRxSxxxxxxxxxxA/exported/vocab.nnen.spm.gz', 'lex.50.50.nnen.s2t.bin': 'models/nn-en/statmt_xxxxxxxxRxSxxxxxxxxxxA/exported/lex.50.50.nnen.s2t.bin.gz' } },
  no: { model: 'model.noen.intgemm.alphas.bin', srcVocab: 'vocab.noen.spm', tgtVocab: 'vocab.noen.spm', lex: 'lex.50.50.noen.s2t.bin', paths: { 'model.noen.intgemm.alphas.bin': 'models/no-en/h1-2025_YKogHXi6Q4es3P7fEWEaBw/exported/model.noen.intgemm.alphas.bin.gz', 'vocab.noen.spm': 'models/no-en/h1-2025_YKogHXi6Q4es3P7fEWEaBw/exported/vocab.noen.spm.gz', 'vocab.noen.spm': 'models/no-en/h1-2025_YKogHXi6Q4es3P7fEWEaBw/exported/vocab.noen.spm.gz', 'lex.50.50.noen.s2t.bin': 'models/no-en/h1-2025_YKogHXi6Q4es3P7fEWEaBw/exported/lex.50.50.noen.s2t.bin.gz' } },
  pl: { model: 'model.plen.intgemm.alphas.bin', srcVocab: 'vocab.plen.spm', tgtVocab: 'vocab.plen.spm', lex: 'lex.50.50.plen.s2t.bin', paths: { 'model.plen.intgemm.alphas.bin': 'models/pl-en/retrain_hr_HLLa6ZwsSomB0kyBr7Iz6w/exported/model.plen.intgemm.alphas.bin.gz', 'vocab.plen.spm': 'models/pl-en/retrain_hr_HLLa6ZwsSomB0kyBr7Iz6w/exported/vocab.plen.spm.gz', 'vocab.plen.spm': 'models/pl-en/retrain_hr_HLLa6ZwsSomB0kyBr7Iz6w/exported/vocab.plen.spm.gz', 'lex.50.50.plen.s2t.bin': 'models/pl-en/retrain_hr_HLLa6ZwsSomB0kyBr7Iz6w/exported/lex.50.50.plen.s2t.bin.gz' } },
  pt: { model: 'model.pten.intgemm.alphas.bin', srcVocab: 'vocab.pten.spm', tgtVocab: 'vocab.pten.spm', lex: 'lex.50.50.pten.s2t.bin', paths: { 'model.pten.intgemm.alphas.bin': 'models/pt-en/retrain_hr_drxrs5bGSsOWvfK9lyZISw/exported/model.pten.intgemm.alphas.bin.gz', 'vocab.pten.spm': 'models/pt-en/retrain_hr_drxrs5bGSsOWvfK9lyZISw/exported/vocab.pten.spm.gz', 'vocab.pten.spm': 'models/pt-en/retrain_hr_drxrs5bGSsOWvfK9lyZISw/exported/vocab.pten.spm.gz', 'lex.50.50.pten.s2t.bin': 'models/pt-en/retrain_hr_drxrs5bGSsOWvfK9lyZISw/exported/lex.50.50.pten.s2t.bin.gz' } },
  ro: { model: 'model.roen.intgemm.alphas.bin', srcVocab: 'vocab.roen.spm', tgtVocab: 'vocab.roen.spm', lex: 'lex.50.50.roen.s2t.bin', paths: { 'model.roen.intgemm.alphas.bin': 'models/ro-en/spring-2024_RwH0W_MDRK2BmZA6VzAmBg/exported/model.roen.intgemm.alphas.bin.gz', 'vocab.roen.spm': 'models/ro-en/spring-2024_RwH0W_MDRK2BmZA6VzAmBg/exported/vocab.roen.spm.gz', 'vocab.roen.spm': 'models/ro-en/spring-2024_RwH0W_MDRK2BmZA6VzAmBg/exported/vocab.roen.spm.gz', 'lex.50.50.roen.s2t.bin': 'models/ro-en/spring-2024_RwH0W_MDRK2BmZA6VzAmBg/exported/lex.50.50.roen.s2t.bin.gz' } },
  ru: { model: 'model.ruen.intgemm.alphas.bin', srcVocab: 'vocab.ruen.spm', tgtVocab: 'vocab.ruen.spm', lex: 'lex.50.50.ruen.s2t.bin', paths: { 'model.ruen.intgemm.alphas.bin': 'models/ru-en/spring-2024_QrcdYgbwS7e7xbhtOSdoNQ/exported/model.ruen.intgemm.alphas.bin.gz', 'vocab.ruen.spm': 'models/ru-en/spring-2024_QrcdYgbwS7e7xbhtOSdoNQ/exported/vocab.ruen.spm.gz', 'vocab.ruen.spm': 'models/ru-en/spring-2024_QrcdYgbwS7e7xbhtOSdoNQ/exported/vocab.ruen.spm.gz', 'lex.50.50.ruen.s2t.bin': 'models/ru-en/spring-2024_QrcdYgbwS7e7xbhtOSdoNQ/exported/lex.50.50.ruen.s2t.bin.gz' } },
  sk: { model: 'model.sken.intgemm.alphas.bin', srcVocab: 'vocab.sken.spm', tgtVocab: 'vocab.sken.spm', lex: 'lex.50.50.sken.s2t.bin', paths: { 'model.sken.intgemm.alphas.bin': 'models/sk-en/spring-2024_TD01UwWXRKacv3wnYeVKbg/exported/model.sken.intgemm.alphas.bin.gz', 'vocab.sken.spm': 'models/sk-en/spring-2024_TD01UwWXRKacv3wnYeVKbg/exported/vocab.sken.spm.gz', 'vocab.sken.spm': 'models/sk-en/spring-2024_TD01UwWXRKacv3wnYeVKbg/exported/vocab.sken.spm.gz', 'lex.50.50.sken.s2t.bin': 'models/sk-en/spring-2024_TD01UwWXRKacv3wnYeVKbg/exported/lex.50.50.sken.s2t.bin.gz' } },
  sl: { model: 'model.slen.intgemm.alphas.bin', srcVocab: 'vocab.slen.spm', tgtVocab: 'vocab.slen.spm', lex: 'lex.50.50.slen.s2t.bin', paths: { 'model.slen.intgemm.alphas.bin': 'models/sl-en/h1-2025_TCeLyjkQRL2YbTXrUhTlAg/exported/model.slen.intgemm.alphas.bin.gz', 'vocab.slen.spm': 'models/sl-en/h1-2025_TCeLyjkQRL2YbTXrUhTlAg/exported/vocab.slen.spm.gz', 'vocab.slen.spm': 'models/sl-en/h1-2025_TCeLyjkQRL2YbTXrUhTlAg/exported/vocab.slen.spm.gz', 'lex.50.50.slen.s2t.bin': 'models/sl-en/h1-2025_TCeLyjkQRL2YbTXrUhTlAg/exported/lex.50.50.slen.s2t.bin.gz' } },
  sq: { model: 'model.sqen.intgemm.alphas.bin', srcVocab: 'vocab.sqen.spm', tgtVocab: 'vocab.sqen.spm', lex: 'lex.50.50.sqen.s2t.bin', paths: { 'model.sqen.intgemm.alphas.bin': 'models/sq-en/h1-2025_I8xy7KMeQoe3mMEV3umzfQ/exported/model.sqen.intgemm.alphas.bin.gz', 'vocab.sqen.spm': 'models/sq-en/h1-2025_I8xy7KMeQoe3mMEV3umzfQ/exported/vocab.sqen.spm.gz', 'vocab.sqen.spm': 'models/sq-en/h1-2025_I8xy7KMeQoe3mMEV3umzfQ/exported/vocab.sqen.spm.gz', 'lex.50.50.sqen.s2t.bin': 'models/sq-en/h1-2025_I8xy7KMeQoe3mMEV3umzfQ/exported/lex.50.50.sqen.s2t.bin.gz' } },
  sr: { model: 'model.sren.intgemm.alphas.bin', srcVocab: 'vocab.sren.spm', tgtVocab: 'vocab.sren.spm', lex: 'lex.50.50.sren.s2t.bin', paths: { 'model.sren.intgemm.alphas.bin': 'models/sr-en/spring-2024_H5GCfsx4SnqOP4YFIQdkdA/exported/model.sren.intgemm.alphas.bin.gz', 'vocab.sren.spm': 'models/sr-en/spring-2024_H5GCfsx4SnqOP4YFIQdkdA/exported/vocab.sren.spm.gz', 'vocab.sren.spm': 'models/sr-en/spring-2024_H5GCfsx4SnqOP4YFIQdkdA/exported/vocab.sren.spm.gz', 'lex.50.50.sren.s2t.bin': 'models/sr-en/spring-2024_H5GCfsx4SnqOP4YFIQdkdA/exported/lex.50.50.sren.s2t.bin.gz' } },
  sv: { model: 'model.sven.intgemm.alphas.bin', srcVocab: 'vocab.sven.spm', tgtVocab: 'vocab.sven.spm', lex: 'lex.50.50.sven.s2t.bin', paths: { 'model.sven.intgemm.alphas.bin': 'models/sv-en/spring-2024_ObaRXwXeSW6HA_-J5_dE-g/exported/model.sven.intgemm.alphas.bin.gz', 'vocab.sven.spm': 'models/sv-en/spring-2024_ObaRXwXeSW6HA_-J5_dE-g/exported/vocab.sven.spm.gz', 'vocab.sven.spm': 'models/sv-en/spring-2024_ObaRXwXeSW6HA_-J5_dE-g/exported/vocab.sven.spm.gz', 'lex.50.50.sven.s2t.bin': 'models/sv-en/spring-2024_ObaRXwXeSW6HA_-J5_dE-g/exported/lex.50.50.sven.s2t.bin.gz' } },
  ta: { model: 'model.taen.intgemm.alphas.bin', srcVocab: 'vocab.taen.spm', tgtVocab: 'vocab.taen.spm', lex: 'lex.50.50.taen.s2t.bin', paths: { 'model.taen.intgemm.alphas.bin': 'models/ta-en/h1-2025_SCQIuddKRXKyysmEsTGv-A/exported/model.taen.intgemm.alphas.bin.gz', 'vocab.taen.spm': 'models/ta-en/h1-2025_SCQIuddKRXKyysmEsTGv-A/exported/vocab.taen.spm.gz', 'vocab.taen.spm': 'models/ta-en/h1-2025_SCQIuddKRXKyysmEsTGv-A/exported/vocab.taen.spm.gz', 'lex.50.50.taen.s2t.bin': 'models/ta-en/h1-2025_SCQIuddKRXKyysmEsTGv-A/exported/lex.50.50.taen.s2t.bin.gz' } },
  te: { model: 'model.teen.intgemm.alphas.bin', srcVocab: 'vocab.teen.spm', tgtVocab: 'vocab.teen.spm', lex: 'lex.50.50.teen.s2t.bin', paths: { 'model.teen.intgemm.alphas.bin': 'models/te-en/h1-2025_YEapi_rWRsSUVTqbBTqupw/exported/model.teen.intgemm.alphas.bin.gz', 'vocab.teen.spm': 'models/te-en/h1-2025_YEapi_rWRsSUVTqbBTqupw/exported/vocab.teen.spm.gz', 'vocab.teen.spm': 'models/te-en/h1-2025_YEapi_rWRsSUVTqbBTqupw/exported/vocab.teen.spm.gz', 'lex.50.50.teen.s2t.bin': 'models/te-en/h1-2025_YEapi_rWRsSUVTqbBTqupw/exported/lex.50.50.teen.s2t.bin.gz' } },
  th: { model: 'model.then.intgemm.alphas.bin', srcVocab: 'vocab.then.spm', tgtVocab: 'vocab.then.spm', lex: 'lex.50.50.then.s2t.bin', paths: { 'model.then.intgemm.alphas.bin': 'models/th-en/new-opuscleaner-en-th_aIiNAAZbRny4ODcYGOMlEA/exported/model.then.intgemm.alphas.bin.gz', 'vocab.then.spm': 'models/th-en/new-opuscleaner-en-th_aIiNAAZbRny4ODcYGOMlEA/exported/vocab.then.spm.gz', 'vocab.then.spm': 'models/th-en/new-opuscleaner-en-th_aIiNAAZbRny4ODcYGOMlEA/exported/vocab.then.spm.gz', 'lex.50.50.then.s2t.bin': 'models/th-en/new-opuscleaner-en-th_aIiNAAZbRny4ODcYGOMlEA/exported/lex.50.50.then.s2t.bin.gz' } },
  tr: { model: 'model.tren.intgemm.alphas.bin', srcVocab: 'vocab.tren.spm', tgtVocab: 'vocab.tren.spm', lex: 'lex.50.50.tren.s2t.bin', paths: { 'model.tren.intgemm.alphas.bin': 'models/tr-en/statmt_xxxxxxxxRxSxxxxxxxxxxA/exported/model.tren.intgemm.alphas.bin.gz', 'vocab.tren.spm': 'models/tr-en/statmt_xxxxxxxxRxSxxxxxxxxxxA/exported/vocab.tren.spm.gz', 'vocab.tren.spm': 'models/tr-en/statmt_xxxxxxxxRxSxxxxxxxxxxA/exported/vocab.tren.spm.gz', 'lex.50.50.tren.s2t.bin': 'models/tr-en/statmt_xxxxxxxxRxSxxxxxxxxxxA/exported/lex.50.50.tren.s2t.bin.gz' } },
  uk: { model: 'model.uken.intgemm.alphas.bin', srcVocab: 'vocab.uken.spm', tgtVocab: 'vocab.uken.spm', lex: 'lex.50.50.uken.s2t.bin', paths: { 'model.uken.intgemm.alphas.bin': 'models/uk-en/spring-2024_WEPBsc-zQWSDn34b5KFscw/exported/model.uken.intgemm.alphas.bin.gz', 'vocab.uken.spm': 'models/uk-en/spring-2024_WEPBsc-zQWSDn34b5KFscw/exported/vocab.uken.spm.gz', 'vocab.uken.spm': 'models/uk-en/spring-2024_WEPBsc-zQWSDn34b5KFscw/exported/vocab.uken.spm.gz', 'lex.50.50.uken.s2t.bin': 'models/uk-en/spring-2024_WEPBsc-zQWSDn34b5KFscw/exported/lex.50.50.uken.s2t.bin.gz' } },
  vi: { model: 'model.vien.intgemm.alphas.bin', srcVocab: 'vocab.vien.spm', tgtVocab: 'vocab.vien.spm', lex: 'lex.50.50.vien.s2t.bin', paths: { 'model.vien.intgemm.alphas.bin': 'models/vi-en/spring-2024_Nc0SHbrgQaiFt4_FmKBXOA/exported/model.vien.intgemm.alphas.bin.gz', 'vocab.vien.spm': 'models/vi-en/spring-2024_Nc0SHbrgQaiFt4_FmKBXOA/exported/vocab.vien.spm.gz', 'vocab.vien.spm': 'models/vi-en/spring-2024_Nc0SHbrgQaiFt4_FmKBXOA/exported/vocab.vien.spm.gz', 'lex.50.50.vien.s2t.bin': 'models/vi-en/spring-2024_Nc0SHbrgQaiFt4_FmKBXOA/exported/lex.50.50.vien.s2t.bin.gz' } },
  zh: { model: 'model.zhen.intgemm.alphas.bin', srcVocab: 'vocab.zhen.spm', tgtVocab: 'vocab.zhen.spm', lex: 'lex.50.50.zhen.s2t.bin', paths: { 'model.zhen.intgemm.alphas.bin': 'models/zh-en/cjk_retrain_base-memory_cNY_yaJCStGwnTeXgW8A5w/exported/model.zhen.intgemm.alphas.bin.gz', 'vocab.zhen.spm': 'models/zh-en/cjk_retrain_base-memory_cNY_yaJCStGwnTeXgW8A5w/exported/vocab.zhen.spm.gz', 'vocab.zhen.spm': 'models/zh-en/cjk_retrain_base-memory_cNY_yaJCStGwnTeXgW8A5w/exported/vocab.zhen.spm.gz', 'lex.50.50.zhen.s2t.bin': 'models/zh-en/cjk_retrain_base-memory_cNY_yaJCStGwnTeXgW8A5w/exported/lex.50.50.zhen.s2t.bin.gz' } },
  zh_hant: { model: 'model.zh_hanten.intgemm.alphas.bin', srcVocab: 'srcvocab.zh_hanten.spm', tgtVocab: 'trgvocab.zh_hanten.spm', lex: 'lex.50.50.zh_hanten.s2t.bin', paths: { 'model.zh_hanten.intgemm.alphas.bin': 'models/zh_hant-en/zh_hant_openlid_zh_tw_lr0002_WJi5Ozi7SZWC6hgfD5GhTA/exported/model.zh_hanten.intgemm.alphas.bin.gz', 'srcvocab.zh_hanten.spm': 'models/zh_hant-en/zh_hant_openlid_zh_tw_lr0002_WJi5Ozi7SZWC6hgfD5GhTA/exported/srcvocab.zh_hanten.spm.gz', 'trgvocab.zh_hanten.spm': 'models/zh_hant-en/zh_hant_openlid_zh_tw_lr0002_WJi5Ozi7SZWC6hgfD5GhTA/exported/trgvocab.zh_hanten.spm.gz', 'lex.50.50.zh_hanten.s2t.bin': 'models/zh_hant-en/zh_hant_openlid_zh_tw_lr0002_WJi5Ozi7SZWC6hgfD5GhTA/exported/lex.50.50.zh_hanten.s2t.bin.gz' } },
};

function getLanguageName(code) {
  const lang = LANGUAGES.find(l => l.code === code);
  return lang ? lang.name : code;
}

function getModelFiles(from, to) {
  if (from === 'en') return FROM_ENGLISH[to];
  if (to === 'en') return TO_ENGLISH[from];
  return null;
}

function getTranslationPairs(from, to) {
  if (from === to) return [];
  if (from === 'en') return [{ from: 'en', to }];
  if (to === 'en') return [{ from, to: 'en' }];
  return [{ from, to: 'en' }, { from: 'en', to }];
}

function getModelFileList(from, to) {
  const files = getModelFiles(from, to);
  if (!files) return [];
  const unique = new Set([files.model, files.srcVocab, files.tgtVocab, files.lex]);
  return [...unique];
}

function getDownloadUrl(from, to, filename) {
  const files = getModelFiles(from, to);
  if (!files || !files.paths || !files.paths[filename]) return null;
  return `${BASE_URL}/${files.paths[filename]}`;
}

function getRequiredLanguages(from, to) {
  if (from === to) return [];
  if (from === 'en') return [to];
  if (to === 'en') return [from];
  return [from, to];
}

export { LANGUAGES, FROM_ENGLISH, TO_ENGLISH, BASE_URL, getLanguageName, getModelFiles, getTranslationPairs, getModelFileList, getDownloadUrl, getRequiredLanguages };
